version: "3.9"

services:
  app:
    build: ./app
    depends_on:
      - redis
    stdin_open: true
    tty: true

  worker:
    build: ./worker
    depends_on:
      - redis
    stdin_open: true
    tty: true

  redis:
    image: redis
    ports:
      - 6379:6379
